version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - db_network
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
  python:
    build:
      context: ./docker/python
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
    ports:
      - "8888:8888"  # Expose the Python (e.g., Jupyter) service on port 8888
networks:
  db_network:
